name: Cl
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Install winget
      run: |
        start "ms-windows-store://pdp/?productid=9NBLGGH4NNS1&mode=mini"
    - name: Update runner
      run: |
        for ($i = 0; $i -lt 10; $i++) {
          try {
            $wingetPath = (Get-AppxPackage -Name "Microsoft.DesktopAppInstaller").InstallLocation + "\winget.exe"
            & $wingetPath upgrade --all --silent
            break
          } catch {
            Start-Sleep -Seconds 5
          }
        }
    - name: Print Windows version
      run: |
        Get-ComputerInfo | select WindowsProductName, WindowsVersion
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
